services:
  lucee:
    image: ${LUCEE_IMAGE}
    ports:
      - "${LUCEE_PORT}:80"
    restart: always
    container_name: ${LUCEE_CONTAINER_NAME}
    environment:
      - LUCEE_ADMIN_PASSWORD=${LUCEE_ADMIN_PASSWORD}
      - UMASK=0000
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - userdata_volume:/var/www/userdata
    networks:
      - saaster_net

  mysql:
    depends_on:
      - lucee
    image: mysql:8.1
    restart: always
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - saaster_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 -u root --password=${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      retries: 10

  flyway:
    image: flyway/flyway:latest
    container_name: ${FLYWAY_CONTAINER_NAME}
    environment:
      - FLYWAY_URL=jdbc:mysql://${MYSQL_CONTAINER_NAME}:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
      - FLYWAY_TABLE=flyway_${FLYWAY_DB_FOLDER}
    command: -locations=filesystem:/flyway/${FLYWAY_DB_FOLDER} ${FLYWAY_MIGRATION_TYPE}
    volumes:
      - ./config/db/${FLYWAY_DB_FOLDER}:/flyway/${FLYWAY_DB_FOLDER}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - saaster_net

  inbucket:
    image: inbucket/inbucket
    container_name: ${INBUCKET_CONTAINER_NAME}
    restart: always
    ports:
      - "${INBUCKET_WEB_PORT}:9000"
      - "${INBUCKET_SMTP_PORT}:2500"
      - "${INBUCKET_POP3_PORT}:1100"
    volumes:
      - inbucket_welcomepage:/config
      - inbucket_data:/storage
    networks:
      - saaster_net

volumes:
  userdata_volume:
    name: ${COMPOSE_PROJECT_NAME}_userdata_volume
  db_volume:
    name: ${COMPOSE_PROJECT_NAME}_db_volume
  inbucket_welcomepage:
    name: ${COMPOSE_PROJECT_NAME}_inbucket_welcomepage
  inbucket_data:
    name: ${COMPOSE_PROJECT_NAME}_inbucket_data

networks:
  saaster_net:
    driver: bridge
