# ==========================================================
# Custom NGINX Configuration File
#
# This file is intended for developer-specific NGINX settings.
# You can define additional rules, headers, location blocks,
# or other configurations without modifying the default setup.
#
# Do NOT create a new `server {}` block here!
# This file is included inside the main server block.
#
# Example:
# add_header X-Frame-Options SAMEORIGIN;
# location /custom-api/ {
#     proxy_pass http://backend_service;
# }
# ==========================================================
